---
title: "Building the MIxT web application"
author: "Vanessa Dumeaux"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The MIxT web application is designed for exploring the results from the MIxT
analysis comparing transcriptional profiles from two matched tissues across
individuals. 

For a more detailed description of the ideas and design of the MIxT web
application please refer to
["Building Applications For Interactive Data Exploration In Systems Biology" by Fjukstad et al.](biorxiv.org/content/early/2017/05/24/141630) 
and the source code [here](https://github.com/fjukstad/mixt). 

# The mixtApp package 
To build the MIxT web application, your will need the [mixtApp](https://github.com/vdumeaux/mixtApp), a wrapper package  calling the mixtR functions and storing pre-computed 
data objects. 

If you want to modify the data, you can
easily rebuild the web application as follow.

First clone down the  [mixtApp](https://github.com/vdumeaux/mixtApp)
repository: 

```
$ git clone https://github.com/vdumeaux/mixtApp.git
```

Then `cd` into the `mixtApp` directory and add the pre-computed data outputs 
you obtained from the mixtR package in the `data/` folder.
To save the data objects, you can modify the 
data url in `data-raw/datasets.R` and run the script:
```
$ R -f data-raw/datasets.R
```
You can also replace the data objects manually. Please make sure that the objects
name and format match the description detailed in the mixtR vignette.

You then need to rebuild the mixtApp package containing the new data using
```
$ R CMD INSTALL .
```

Next up is building the docker container with your new mixtApp package.

Still in the `mixtApp/` directory, run: 
```
docker build -t compute-service .
docker run --name=compute-service -t compute-service
```

which build and run the container. 
It should appear with the `docker ps` command: 

```
 docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
08c9889b705e        compute-service     "/bin/sh -c 'go ru..."   4 seconds ago       Up 4 seconds        80/tcp              compute-service
```

The compute service is now running, so next up is starting the web application
container. This is luckily a one liner: 

```
docker run -p 8000:80 --link compute-service -e COMPUTE_SERVICE=compute-service:80 --name=mixt -t fjukstad/mixt-stroma
```

That's it!  You can now visit the application that displays you own data running on
[localhost:8000](http://localhost:8000). 

If you need more details on the docker commands you can have a look
at[docs.docker.com](https://docs.docker.com).
